---

 - hosts: all
   become: true
   tasks:
 
   - name: Change the SSHD config to secure
     copy:
       src: local_ssh_config # local dir
       dest: /etc/ssh/sshd_config
       owner: root
       group: root
       mode: 0440

   - name: SSH dir permissions change to 700
     ansible.builtin.file:
        path: ~/.ssh
        owner: root
        group: root
        mode: '0700'

   - name: SSH authorized_keys permissions change to 600
     ansible.builtin.file:
        path: ~/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0600'
 
   - name: Stop and Start ssh
     service:
       name: ssh
       state: restarted   